CREATE DATABASE BOOK;

SHOW DATABASES;

USE BOOK;

CREATE TABLE BOOK.TABELA(
ID INT AUTO_INCREMENT,
NOME VARCHAR (255) NOT NULL,
AUTOR VARCHAR (255) NOT NULL,
SEXO  VARCHAR (25) NOT NULL,
NUMERO_DE_PAGINAS INT NOT NULL,
EDITORA VARCHAR (255) NOT NULL,
VALOR_CAPA_COMUM INT NOT NULL,
VALOR_KINDLE INT NOT NULL,
ANO INT NOT NULL,
PRIMARY KEY (ID)
);

INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('PAI RICO, PAI POBRE', 'ROBERT T.KIYOUSAKI ', 'MASCULINO', 336,'ALTA BOOKS', 61.5 , 58.45, 2018);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO) 
VALUES ('MINDSET', 'CAROL S DWECK ', 'FEMININO', 312,'OBJETIVA',38.99, 14.95, 2017);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('COMO FAZER AMIGOS E INFLUENCIAR PESSOAS', 'DALE CANEGIE','MASCULINO', 256,'SEXTANTE',38.99, 33.24, 2019);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('A CABANA', 'WILLIAM P YOUNG', 'MASCULINO', 240,'ARQUEIRO',35.99, 17.90, 2008);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO) 
VALUES ('O PODER DO HABITO', 'CHARLES DUHIGG', 'MASCULINO', 408,'OBJETIVA',42.99, 29.90, 2012);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO) 
VALUES ('CODIGO LIMPO', 'ROBERT C MARTIN', 'MASCULINO', 425,'ALTA BOOKS',91.99, 87.39, 2009);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('ESSENCIALISMO', 'GREG MCKEOWN ', 'MASCULINO', 272,'SEXTANTE',53.58, 33.24, 2015);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('ME POUPE!', 'NATHALIA ARCURI ', 'FEMININO', 176,'SEXTANTE',32.86, 17.09, 2018);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO)
 VALUES ('COMECE PELO PORQUE', 'SIMON SINEK ', 'MASCULINO', 256,'SEXTANTE',50.58, 24.91, 2018);
INSERT INTO BOOK.TABELA (NOME, AUTOR, SEXO, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, VALOR_KINDLE, ANO) 
VALUES ('O ALQUIMISTA', 'PAULO COELHO', 'MASCULINO', 206,'PARALELA',24.70, 14.70, 2017);

-- SELECIONAR TODAS AS TABELAS

SELECT * FROM BOOK.TABELA;

-- TRUNCATE TABELA; --APAGA A TABELA


 
 -- SELECIONA APENAS ID, NOME E EDITORA +
SELECT ID, NOME, EDITORA FROM BOOK.TABELA;

-- MOSTRA ID, EDITORA E SEXO MASCULINO +
SELECT ID, EDITORA, SEXO FROM TABELA WHERE SEXO = 'MASCULINO';

-- MOSTRA NOME, PAGINAS E SEXO FEMININO +
SELECT ID, NOME, NUMERO_DE_PAGINAS, SEXO FROM TABELA WHERE SEXO = 'FEMININO';

-- MOSTRA NOME, EDITORA, ANO A PARTI DE 2017 +
SELECT ID, NOME, ANO FROM TABELA WHERE ANO >= 2017;

-- MOSTRAR NOME, SEXO MASCULINO, EDITORA SEXTANTE OU ALTA BOOKS+
SELECT ID, NOME, SEXO, EDITORA FROM TABELA WHERE SEXO = 'MASCULINO' AND EDITORA = 'SEXTANTE' OR 'ALTA BOOKS';

-- MOSTRAR NOME, AUTOR, NUMERO DE PAGINAS, EDITORA, ANO E VALOR CAPA COMUM+
SELECT ID, NOME, AUTOR, NUMERO_DE_PAGINAS, EDITORA, VALOR_CAPA_COMUM, ANO FROM TABELA; 

-- MOSTRAR NOME, AUTOR, NUMERO DE PAGINAS, VALOR KINDLE+
SELECT ID, NOME, AUTOR, NUMERO_DE_PAGINAS, VALOR_KINDLE FROM TABELA;

-- MOSTRAR AUTOR, NOME, EDITORA+
SELECT ID, AUTOR, EDITORA, NOME FROM TABELA WHERE EDITORA = 'SEXTANTE';

-- MOSTRAR NOME, AUTOR, VALOR DA CAPA COMUM E DO KINDLE;
SELECT ID, NOME, AUTOR, VALOR_CAPA_COMUM, VALOR_KINDLE FROM TABELA;